//-------------CLASS----------
export const SAVE_GET_LIST_CLASS = "SAVE_GET_LIST_CLASS";
export const SET_MODAL_CLASS_OPEN = "SET_MODAL_CLASS_OPEN";
export const SET_SELECTED_CLASS = "SET_SELECTED_CLASS";
export const SAVE_CREATE_CLASS = "SAVE_CREATE_CLASS";
export const SET_VIEW_CLASS_MODAL = "SET_VIEW_CLASS_MODAL";
export const SET_VIEW_STUDENT_IN_CLASS = "SET_VIEW_STUDENT_IN_CLASS";


//--------------STUDENT---------
export const SET_ADD_STUDENT_MODAL = "SET_ADD_STUDENT_MODAL";
export const SET_EDIT_STUDENT_MODAL = "SET_EDIT_STUDENT_MODAL";
export const SET_VIEW_STUDENT_MODAL = "SET_VIEW_STUDENT_MODAL";

//--------------SUBJECT---------
export const SET_ADD_SUBJECT_MODAL = "SET_ADD_SUBJECT_MODAL";
export const SET_EDIT_SUBJECT_MODAL = "SET_EDIT_SUBJECT_MODAL";
